swagger: "2.0"
info:
  title: "Authentication Microservice"
  description: A authentication microservice for generating tokens.
  contact:
    name: Murat Mayadag
    url: https://github.com/mmayadag
  license:
    name: MIT
    url: https://github.com/mmayadag/s3-auth/blob/master/LICENSE
  version: 1.0.0
basePath: /
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  token:
    type: basic
paths:
  /login:
    get:
      description: Returns a token to be used for accessing the monolith's secure endpoints.
      responses:
        200:
          description: Token
          schema:
            $ref: '#/definitions/Token'
definitions:
  Token:
    required:
      - token
    properties:
      token:
        type: string
    example:
      token: asdfadsflkjewrlkjsdal;jxc21335